name: panaderia_delipan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  cupertino_icons: ^1.0.2
  geolocator: ^11.0.0
  http: ^1.2.1
  google_maps_flutter: ^2.6.0
  firebase_auth: ^5.5.4
  google_sign_in: ^6.1.5
  image_picker: ^1.1.2
  firebase_storage: ^12.4.6
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
